services:
  - type: web
    name: task-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: API_PREFIX
        value: /api
      - key: API_VERSION
        value: v1
    autoDeploy: true
